## Import Libaries

In [1]:
import pandas as pd
import numpy as np

In [2]:
# Load the final dataset
new_df = pd.read_csv("Dataset/new_df.csv")

new_df.head()

In [3]:
new_df['tags'][0]

'in the 22nd century, a paraplegic marine is dispatched to the moon pandora on a unique mission, but becomes torn between following orders and protecting an alien civilization. action adventure fantasy sciencefiction cultureclash future spacewar spacecolony society spacetravel futuristic romance space alien tribe alienplanet cgi marine soldier battle loveaffair antiwar powerrelations mindandsoul 3d samworthington zoesaldana sigourneyweaver jamescameron'

## Stemming

In [4]:
import nltk

In [5]:
from nltk.stem.porter import PorterStemmer

stemmer = PorterStemmer()

In [6]:
stemmer.stem('running')

'run'

In [7]:
def stem(text):
    y = []   # Define a empty list

    for i in text.split():     # `text.spilit()` String converted to a list
        y.append(stemmer.stem(i))

    return " ".join(y)      # Again convert List to String

In [8]:
stem('in the 22nd century, a paraplegic marine is dispatched to the moon pandora on a unique mission, but becomes torn between following orders and protecting an alien civilization. action adventure fantasy sciencefiction cultureclash future spacewar spacecolony society spacetravel futuristic romance space alien tribe alienplanet cgi marine soldier battle loveaffair antiwar powerrelations mindandsoul 3d samworthington zoesaldana sigourneyweaver jamescameron')

'in the 22nd century, a parapleg marin is dispatch to the moon pandora on a uniqu mission, but becom torn between follow order and protect an alien civilization. action adventur fantasi sciencefict cultureclash futur spacewar spacecoloni societi spacetravel futurist romanc space alien tribe alienplanet cgi marin soldier battl loveaffair antiwar powerrel mindandsoul 3d samworthington zoesaldana sigourneyweav jamescameron'

In [9]:
new_df['tags'].apply(stem)

0       in the 22nd century, a parapleg marin is dispa...
1       captain barbossa, long believ to be dead, ha c...
2       a cryptic messag from bond’ past send him on a...
3       follow the death of district attorney harvey d...
4       john carter is a war-weary, former militari ca...
                              ...                        
4801    el mariachi just want to play hi guitar and ca...
4802    a newlyw couple' honeymoon is upend by the arr...
4803    "signed, sealed, delivered" introduc a dedic q...
4804    when ambiti new york attorney sam is sent to s...
4805    ever sinc the second grade when he first saw h...
Name: tags, Length: 4806, dtype: object

In [10]:
new_df['tags'] = new_df['tags'].apply(stem)

In [11]:
new_df['tags']

0       in the 22nd century, a parapleg marin is dispa...
1       captain barbossa, long believ to be dead, ha c...
2       a cryptic messag from bond’ past send him on a...
3       follow the death of district attorney harvey d...
4       john carter is a war-weary, former militari ca...
                              ...                        
4801    el mariachi just want to play hi guitar and ca...
4802    a newlyw couple' honeymoon is upend by the arr...
4803    "signed, sealed, delivered" introduc a dedic q...
4804    when ambiti new york attorney sam is sent to s...
4805    ever sinc the second grade when he first saw h...
Name: tags, Length: 4806, dtype: object

## TF-IDF

In [12]:
from sklearn.feature_extraction.text import TfidfVectorizer

vectorizer = TfidfVectorizer(max_features=5000, stop_words='english')

In [13]:
vectors = vectorizer.fit_transform(new_df['tags']).toarray()

In [14]:
vectors

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [15]:
vectors.shape

(4806, 5000)

In [16]:
words = vectorizer.get_feature_names_out()
print(words[:100])       # See first 100 words  

['000' '007' '10' '100' '11' '12' '13' '14' '15' '16' '17' '17th' '18'
 '18th' '18thcenturi' '19' '1910' '1920' '1930' '1940' '1944' '1950'
 '1950s' '1960' '1960s' '1970' '1970s' '1971' '1974' '1976' '1980' '1985'
 '1990' '1999' '19th' '19thcenturi' '20' '200' '2003' '2009' '20th' '21st'
 '23' '24' '25' '30' '300' '3d' '40' '50' '500' '60' '70' '80' 'aaron'
 'aaroneckhart' 'abandon' 'abduct' 'abigailbreslin' 'abil' 'abl' 'aboard'
 'abov' 'abus' 'academ' 'academi' 'accept' 'access' 'accid' 'accident'
 'acclaim' 'accompani' 'accomplish' 'account' 'accus' 'ace' 'achiev'
 'acquaint' 'act' 'action' 'actionhero' 'activ' 'activist' 'activities'
 'actor' 'actress' 'actual' 'ad' 'adam' 'adamsandl' 'adamshankman' 'adapt'
 'add' 'addict' 'adjust' 'admir' 'admit' 'adolesc' 'adopt' 'ador']


## Cosine similarity

In [17]:
from sklearn.metrics.pairwise import cosine_similarity

In [18]:
similarity = cosine_similarity(vectors)

In [19]:
similarity

array([[1.        , 0.02203984, 0.03038546, ..., 0.02319866, 0.        ,
        0.        ],
       [0.02203984, 1.        , 0.0129118 , ..., 0.01700865, 0.        ,
        0.00642518],
       [0.03038546, 0.0129118 , 1.        , ..., 0.01628553, 0.        ,
        0.        ],
       ...,
       [0.02319866, 0.01700865, 0.01628553, ..., 1.        , 0.01860761,
        0.02850017],
       [0.        , 0.        , 0.        , ..., 0.01860761, 1.        ,
        0.0197017 ],
       [0.        , 0.00642518, 0.        , ..., 0.02850017, 0.0197017 ,
        1.        ]])

In [20]:
similarity.shape

(4806, 4806)

In [21]:
similarity[0]

array([1.        , 0.02203984, 0.03038546, ..., 0.02319866, 0.        ,
       0.        ])

- ### Now create a function ,in this function pass one movie then this function return 5 similar movies name.

In [34]:
def recommend(movie):
    # Find the index of the movie whose title matches 'movie'
    movie_index = new_df[new_df['title'] == movie].index[0]        

    # Get the similarity scores of the selected movie with all movies.
    distances = similarity[movie_index]    
    # Sort movies by similarity score (highest to lowest) and select the top 5 similar movies
    movies_list = sorted(list(enumerate(distances)), reverse=True, key=lambda x:x[1])[1:6] 

    for i in movies_list:
        # Get the title of the recommended movie and print it.
        print(new_df.iloc[i[0]].title)

In [35]:
recommend('Batman Begins')

The Dark Knight
The Dark Knight Rises
Batman v Superman: Dawn of Justice
Batman
Batman Returns


In [32]:
# def recommend(movie):
#     # Find the index of the movie whose title matches 'movie'
#     movie_index = new_df[new_df['title'] == movie].index[0]        

#     # Get the similarity scores of the selected movie with all movies.
#     distances = similarity[movie_index]    
#     # Sort movies by similarity score (highest to lowest) and select the top 5 similar movies
#     movies_list = sorted(list(enumerate(distances)), reverse=True, key=lambda x:x[1])[1:6] 

#     recommendations = []

#     for i in movies_list:
#         recommendations.append(new_df.iloc[i[0]].title)

#     return recommendations

In [33]:
# test_movies = [
#     "Avatar",
#     "Batman Begins",
#     "Spider-Man",
#     "Titanic"
# ]

# for movie in test_movies:
#     print("\nMovie:", movie)
#     print("TF-IDF:", recommend(movie))


Movie: Avatar
TF-IDF: ['Aliens', 'Falcon Rising', 'Battle: Los Angeles', 'Aliens vs Predator: Requiem', 'Apollo 18']

Movie: Batman Begins
TF-IDF: ['The Dark Knight', 'The Dark Knight Rises', 'Batman v Superman: Dawn of Justice', 'Batman', 'Batman Returns']

Movie: Spider-Man
TF-IDF: ['Spider-Man 3', 'Spider-Man 2', 'Arachnophobia', 'The Amazing Spider-Man 2', 'The Amazing Spider-Man']

Movie: Titanic
TF-IDF: ['Ghost Ship', 'Poseidon', 'Pirates of the Caribbean: On Stranger Tides', 'The Rose', 'Dear Frankie']


-----------

## Final Observation

- I manually compared the recommendations generated by CountVectorizer (BOW) and TF-IDF for a few movies such as Avatar, Batman Begins, Spider-Man, and Titanic. Both techniques can generate meaningful recommendations, but the exact recommendations and rankings are different.

- CountVectorizer considers word frequency, while TF-IDF reduces the importance of commonly occurring words. Since my published project uses CountVectorizer (BOW), I kept it as the final approach. The TF-IDF version was created only for comparison and experimentation.